frontend_notice:
        resource: "@FrontendBundle/Resources/config/routing/notice.yml"
        prefix:   /notice

frontend_events:
        resource: "@FrontendBundle/Resources/config/routing/events.yml"
        prefix:   /events

frontend_typeevent:
        resource: "@FrontendBundle/Resources/config/routing/typeevent.yml"
        prefix:   /typeevent

frontend_prices:
        resource: "@FrontendBundle/Resources/config/routing/prices.yml"
        prefix:   /prices

frontend_spend:
        resource: "@FrontendBundle/Resources/config/routing/spend.yml"
        prefix:   /spend

frontend_spend:
        resource: "@FrontendBundle/Resources/config/routing/auth.yml"
        prefix:   /auth
